"""
Type stubs for the _obu native Rust extension module.

These stubs enable IDE autocompletion (VS Code, PyCharm), mypy, and
pyright support for the obu Python bindings.

Only the classes shipped in the default wheel are stubbed. The
testing-only ``Zmock1*`` classes (``mock`` feature) and the deprecated
``Legacy`` codec (``legacy`` feature) are not part of the published
surface and are intentionally omitted.
"""

from typing import Optional

__version__: str

# ============================================================================
# Fixed-format codec classes
# ============================================================================

class UpcbcC32:
    def __init__(self, secret: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def secret(self) -> str: ...
    @property
    def secret_hex(self) -> str: ...
    @property
    def secret_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class UpcbcB32:
    def __init__(self, secret: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def secret(self) -> str: ...
    @property
    def secret_hex(self) -> str: ...
    @property
    def secret_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class UpcbcB64:
    def __init__(self, secret: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def secret(self) -> str: ...
    @property
    def secret_hex(self) -> str: ...
    @property
    def secret_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class UpcbcHex:
    def __init__(self, secret: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def secret(self) -> str: ...
    @property
    def secret_hex(self) -> str: ...
    @property
    def secret_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class ZdcbcC32:
    def __init__(self, secret: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def secret(self) -> str: ...
    @property
    def secret_hex(self) -> str: ...
    @property
    def secret_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class ZdcbcB32:
    def __init__(self, secret: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def secret(self) -> str: ...
    @property
    def secret_hex(self) -> str: ...
    @property
    def secret_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class ZdcbcB64:
    def __init__(self, secret: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def secret(self) -> str: ...
    @property
    def secret_hex(self) -> str: ...
    @property
    def secret_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class ZdcbcHex:
    def __init__(self, secret: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def secret(self) -> str: ...
    @property
    def secret_hex(self) -> str: ...
    @property
    def secret_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

# ============================================================================
# Flexible interfaces
# ============================================================================

class Obu:
    def __init__(self, format: str, secret: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def secret(self) -> str: ...
    @property
    def secret_hex(self) -> str: ...
    @property
    def secret_bytes(self) -> bytes: ...
    def set_format(self, format: str) -> None: ...
    def set_scheme(self, scheme: str) -> None: ...
    def set_encoding(self, encoding: str) -> None: ...
    def __repr__(self) -> str: ...

class Omnibu:
    def __init__(self, secret: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str, format: str) -> str: ...
    def dec(self, obtext: str, format: str) -> str: ...
    @property
    def secret(self) -> str: ...
    @property
    def secret_hex(self) -> str: ...
    @property
    def secret_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

# ============================================================================
# Secret generation functions
# ============================================================================

def generate_secret() -> str: ...
def generate_secret_bytes() -> bytes: ...

# ============================================================================
# Convenience functions
# ============================================================================

def enc(plaintext: str, format: str, secret: str) -> str: ...
def dec(obtext: str, format: str, secret: str) -> str: ...
def enc_keyless(plaintext: str, format: str) -> str: ...
def dec_keyless(obtext: str, format: str) -> str: ...

# ============================================================================
# Exception hierarchy
# ============================================================================

class ObuError(Exception):
    """Base class for all obu exceptions."""
    ...

class InvalidSecret(ObuError):
    """Bad hex secret / wrong length."""
    ...

class InvalidFormat(ObuError):
    """Unknown scheme / encoding / malformed format string."""
    ...

class EncryptionFailed(ObuError):
    """Empty plaintext / 0x01 pad-byte rejection."""
    ...

class DecryptionFailed(ObuError):
    """obtext-decode, block-length, payload-shape, or UTF-8 failure."""
    ...
